---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: webserver
  name: webserver-service
  namespace: default
spec:
  ports:
  - protocol: TCP
    name: webserver-port
    port: 80
#    targetPort: 80
#  type: NodePort
#  type: LoadBalancer
  selector:
    name: webserver
