kind: ReplicationController
apiVersion: v1
metadata:
  name: webserver-controller
  labels:
    name: webserver
spec:
  replicas: 1
  selector:
    name: webserver
  template:
    spec:
      containers:
        - name: apache-frontend
          image: localhost:5000/rhel7webapp
          ports:
            - containerPort: 80
    metadata:
      labels:
        name: webserver
        uses: db
